# FastAPI ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: default
data:
  DATABASE_URL: "mysql+pymysql://root:password@mysql-service:3306/todoapp"

---
# FastAPI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: default
  labels:
    app: fastapi-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-todo
  template:
    metadata:
      labels:
        app: fastapi-todo
    spec:
      containers:
      - name: fastapi-todo
        image: asia-southeast1-docker.pkg.dev/verdant-bruin-464819-i9/fastapi-todoapp/fastapi-todoapp:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        command: ['sh', '-c']
        args:
        - |
          until mysql -h mysql-service -u root -ppassword -e "SELECT 1;" > /dev/null 2>&1; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          echo "MySQL is ready and accepting connections!"

---
# FastAPI Service
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
  labels:
    app: fastapi-todo
spec:
  selector:
    app: fastapi-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
